// Code generated by dto builder generator; DO NOT EDIT.

package sdk

import ()

func NewCreateComputePoolRequest(
	name AccountObjectIdentifier,
	MinNodes int,
	MaxNodes int,
	InstanceFamily string,
) *CreateComputePoolRequest {
	s := CreateComputePoolRequest{}
	s.name = name
	s.MinNodes = MinNodes
	s.MaxNodes = MaxNodes
	s.InstanceFamily = InstanceFamily
	return &s
}

func (s *CreateComputePoolRequest) WithIfNotExists(IfNotExists *bool) *CreateComputePoolRequest {
	s.IfNotExists = IfNotExists
	return s
}

func (s *CreateComputePoolRequest) WithAutoResume(AutoResume *bool) *CreateComputePoolRequest {
	s.AutoResume = AutoResume
	return s
}

func (s *CreateComputePoolRequest) WithInitiallySuspended(InitiallySuspended *bool) *CreateComputePoolRequest {
	s.InitiallySuspended = InitiallySuspended
	return s
}

func (s *CreateComputePoolRequest) WithAutoSuspendSecs(AutoSuspendSecs *int) *CreateComputePoolRequest {
	s.AutoSuspendSecs = AutoSuspendSecs
	return s
}

func (s *CreateComputePoolRequest) WithComment(Comment *string) *CreateComputePoolRequest {
	s.Comment = Comment
	return s
}

func NewAlterComputePoolRequest(
	name AccountObjectIdentifier,
) *AlterComputePoolRequest {
	s := AlterComputePoolRequest{}
	s.name = name
	return &s
}

func (s *AlterComputePoolRequest) WithIfExists(IfExists *bool) *AlterComputePoolRequest {
	s.IfExists = IfExists
	return s
}

func (s *AlterComputePoolRequest) WithSuspend(Suspend *bool) *AlterComputePoolRequest {
	s.Suspend = Suspend
	return s
}

func (s *AlterComputePoolRequest) WithResume(Resume *bool) *AlterComputePoolRequest {
	s.Resume = Resume
	return s
}

func (s *AlterComputePoolRequest) WithStopAll(StopAll *bool) *AlterComputePoolRequest {
	s.StopAll = StopAll
	return s
}

func (s *AlterComputePoolRequest) WithSet(Set *PropertiesToAlterRequest) *AlterComputePoolRequest {
	s.Set = Set
	return s
}

func NewPropertiesToAlterRequest() *PropertiesToAlterRequest {
	return &PropertiesToAlterRequest{}
}

func (s *PropertiesToAlterRequest) WithMinNodes(MinNodes *int) *PropertiesToAlterRequest {
	s.MinNodes = MinNodes
	return s
}

func (s *PropertiesToAlterRequest) WithMaxNodes(MaxNodes *int) *PropertiesToAlterRequest {
	s.MaxNodes = MaxNodes
	return s
}

func (s *PropertiesToAlterRequest) WithAutoResume(AutoResume *bool) *PropertiesToAlterRequest {
	s.AutoResume = AutoResume
	return s
}

func (s *PropertiesToAlterRequest) WithAutoSuspendSecs(AutoSuspendSecs *int) *PropertiesToAlterRequest {
	s.AutoSuspendSecs = AutoSuspendSecs
	return s
}

func (s *PropertiesToAlterRequest) WithComment(Comment *string) *PropertiesToAlterRequest {
	s.Comment = Comment
	return s
}

func NewDropComputePoolRequest(
	name AccountObjectIdentifier,
) *DropComputePoolRequest {
	s := DropComputePoolRequest{}
	s.name = name
	return &s
}

func (s *DropComputePoolRequest) WithIfExists(IfExists *bool) *DropComputePoolRequest {
	s.IfExists = IfExists
	return s
}

func NewShowComputePoolRequest() *ShowComputePoolRequest {
	return &ShowComputePoolRequest{}
}

func (s *ShowComputePoolRequest) WithLike(Like *Like) *ShowComputePoolRequest {
	s.Like = Like
	return s
}

func (s *ShowComputePoolRequest) WithStartsWith(StartsWith *string) *ShowComputePoolRequest {
	s.StartsWith = StartsWith
	return s
}

func (s *ShowComputePoolRequest) WithLimit(Limit *LimitFrom) *ShowComputePoolRequest {
	s.Limit = Limit
	return s
}

func NewDescribeComputePoolRequest(
	name AccountObjectIdentifier,
) *DescribeComputePoolRequest {
	s := DescribeComputePoolRequest{}
	s.name = name
	return &s
}
